### ISSUE TITLE
Doesn't work with server islands

### ISSUE THREAD

**Issue by LucidityDesign** [JoseDv1/HonoAstroAdapter#1]
First of all great adapter, thanks a lot!
I noticed that it doesn't work with [server islands](https://docs.astro.build/en/reference/configuration-reference/#experimentalserverislands):
Config:
```
export default defineConfig({
    output: 'server',
    experimental: {
        serverIslands: true,
    },
    adapter: honoAstro(),
    integrations: [react(), tailwind()],
});
```
Island component:
```
---
const data = await new Promise((resolve) => {
  setTimeout(() => {
    resolve('Hello, Astro!');
  }, 1000);
});
---
<div>{data}</div>
```
And this is how I embed the island:
```
<Island server:defer>
	<p slot="fallback">Island content...</p>
</Island>
```
Error message:
```
1320 | function renderServerIsland(result, _displayName, props, slots) {
1321 |   return {
1322 |     async render(destination) {
1323 |       const componentPath = props["server:component-path"];
1324 |       const componentExport = props["server:component-export"];
1325 |       const componentId = result.serverIslandNameMap.get(componentPath);
                                 ^
TypeError: undefined is not an object (evaluating 'result.serverIslandNameMap.get')
      at .../dist/server/chunks/astro/server_Dtrth2oi.mjs:1325:27
      at render (.../dist/server/chunks/astro/server_Dtrth2oi.mjs:1322:18)
      at .../dist/server/chunks/astro/server_Dtrth2oi.mjs:949:11
```
When I setup my server with express it works.

**Comment by JoseDv1** [comment]
Thank you for your contribution! ❤️
